#!/usr/bin/env bash
# Build the working tree and install it -- as a pacman package.
#
# Not `install -m755 target/release/lami /usr/local/bin`, which is what this
# used to do. lami declares itself in the core layer, so pacman's database is
# what `lami diff` reads to decide whether lami is installed. A binary dropped
# in /usr/local/bin would shadow the packaged one while pacman went on
# reporting the old version: the tool would be lying about itself.
#
# The version gets a git suffix so `pacman -Q lami` says which commit is on
# the machine.
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"
src="$PWD"

[[ $EUID -eq 0 ]] && { echo "Run as yourself; makepkg refuses root."; exit 1; }

cargo build --release

base="$(sed -n 's/^version = "\(.*\)"/\1/p' Cargo.toml | head -1)"
if git rev-parse --git-dir >/dev/null 2>&1; then
    ver="${base}.r$(git rev-list --count HEAD).$(git rev-parse --short HEAD)"
    git diff --quiet || ver="${ver}.dirty"
else
    ver="$base"
fi
# pacman version strings may not contain a hyphen.
ver="${ver//-/_}"

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

cat > "$work/PKGBUILD" <<PKG
# Generated by install.sh. Packages the binary already built from the working
# tree at $src -- makepkg is not asked to build anything.
pkgname=lami
pkgver=$ver
pkgrel=1
pkgdesc="Layered, declarative system configuration for Arch Linux (working tree)"
arch=('x86_64')
url="https://github.com/pottom/lami"
license=('MIT')
depends=()
options=('!debug' '!strip')
package() {
    install -Dm755 "$src/target/release/lami" "\$pkgdir/usr/bin/lami"
    install -Dm644 "$src/LICENSE" "\$pkgdir/usr/share/licenses/lami/LICENSE"
    install -Dm644 "$src/README.md" "\$pkgdir/usr/share/doc/lami/README.md"
    install -Dm644 "$src/docs/guide.md" "\$pkgdir/usr/share/doc/lami/guide.md"
}
PKG

( cd "$work" && makepkg -f )
sudo pacman -U --noconfirm "$work"/lami-*.pkg.tar.zst

if [[ -e /usr/local/bin/lami ]]; then
    echo
    echo "warning: /usr/local/bin/lami exists and shadows the packaged binary."
    echo "         sudo rm /usr/local/bin/lami"
fi

echo
echo "installed: $(command -v lami)  ($(pacman -Q lami))"
echo "commands:  $(lami --help | sed -n '/Commands:/,/^$/p' | awk 'NR>1 && NF {printf "%s ", $1}')"
