# Managed by lami. Local edits will be overwritten.
[options]
Color
ParallelDownloads = 10
ILoveCandy

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist
