//! The config repo: where it lives, and keeping it in sync with its remote.
//!
//! The config is a git repository, and lami needs to find it before it can
//! parse anything. That pointer cannot live inside the repo itself, so it
//! lives beside it in a small file:
//!
//! ```kdl
//! // ~/.config/lami.kdl
//! repo "git@github.com:you/lami-config.git"
//! path "~/Projects/lami-config"
//! ```
//!
//! Both lines are optional and both have a command line equivalent
//! (`--repo`, `--config-dir`). With neither, lami falls back to
//! `~/.config/lami`.
//!
//! git is shelled out to, for the same reason pacman is: an in-process git
//! library would tie us to its idea of ssh, credential helpers and signing,
//! all of which the user has already configured for the `git` they use.

use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

use crate::color;
use crate::error::{Error, Result};

/// The machine-local pointer to the config repo.
#[derive(Debug, Default)]
pub struct Pointer {
    /// Remote URL, if one was recorded.
    pub repo: Option<String>,
    /// Where the working copy lives on this machine.
    pub path: Option<PathBuf>,
}

/// Where the pointer file lives: `$XDG_CONFIG_HOME/lami.kdl`, else
/// `~/.config/lami.kdl`.
///
/// Deliberately a file next to the `lami/` directory rather than inside it:
/// the directory may be the repo, or may not exist yet.
pub fn pointer_path(home: &Path) -> PathBuf {
    match std::env::var("XDG_CONFIG_HOME") {
        Ok(x) if !x.is_empty() => PathBuf::from(x).join("lami.kdl"),
        _ => home.join(".config").join("lami.kdl"),
    }
}

impl Pointer {
    pub fn load(home: &Path) -> Result<Pointer> {
        let file = pointer_path(home);
        if !file.is_file() {
            return Ok(Pointer::default());
        }
        let src = std::fs::read_to_string(&file).map_err(|source| Error::Io {
            path: file.clone(),
            source,
        })?;
        let doc: kdl::KdlDocument = src.parse()?;
        let mut p = Pointer::default();
        for node in doc.nodes() {
            let val = node
                .entries()
                .iter()
                .find(|e| e.name().is_none())
                .and_then(|e| e.value().as_string())
                .map(str::to_string);
            match (node.name().value(), val) {
                ("repo", Some(v)) => p.repo = Some(v),
                ("path", Some(v)) => p.path = Some(crate::config::expand_home(&v, home)),
                _ => {}
            }
        }
        Ok(p)
    }

    /// Write the pointer file, preserving nothing: it has two lines and is
    /// generated by `lami clone`.
    pub fn save(&self, home: &Path) -> Result<PathBuf> {
        let file = pointer_path(home);
        if let Some(parent) = file.parent() {
            std::fs::create_dir_all(parent).map_err(|source| Error::Io {
                path: parent.to_path_buf(),
                source,
            })?;
        }
        let mut s = String::from(
            "// Where lami finds your config repo. Written by `lami clone`;\n\
             // edit it freely, or override with --repo / --config-dir.\n",
        );
        if let Some(r) = &self.repo {
            s.push_str(&format!("repo {}\n", quote(r)));
        }
        if let Some(p) = &self.path {
            s.push_str(&format!("path {}\n", quote(&tilde(p, home))));
        }
        std::fs::write(&file, s).map_err(|source| Error::Io {
            path: file.clone(),
            source,
        })?;
        Ok(file)
    }
}

fn quote(s: &str) -> String {
    format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\""))
}

/// Render a path back with `~/` if it is under the home directory, so the
/// pointer file stays readable and portable.
fn tilde(p: &Path, home: &Path) -> String {
    match p.strip_prefix(home) {
        Ok(rest) => format!("~/{}", rest.display()),
        Err(_) => p.display().to_string(),
    }
}

// ---------------------------------------------------------------------------

/// git needs the user's ssh keys, agent and credential helpers, none of which
/// survive sudo. So these commands refuse root rather than half-working.
pub fn refuse_root(what: &str) -> Result<()> {
    if unsafe { libc::geteuid() } == 0 {
        return Err(Error::Other(format!(
            "`{what}` talks to your git remote, so run it as yourself, not with sudo.\n\
             Under sudo your ssh agent and credential helper are gone, and any file\n\
             git wrote would end up owned by root."
        )));
    }
    Ok(())
}

fn git(dir: Option<&Path>, args: &[&str]) -> Result<std::process::ExitStatus> {
    let mut c = Command::new("git");
    if let Some(d) = dir {
        c.arg("-C").arg(d);
    }
    c.args(args);
    c.status().map_err(|source| Error::Io {
        path: PathBuf::from("git"),
        source,
    })
}

fn git_out(dir: &Path, args: &[&str]) -> Result<String> {
    let out = Command::new("git")
        .arg("-C")
        .arg(dir)
        .args(args)
        .stderr(Stdio::null())
        .output()
        .map_err(|source| Error::Io {
            path: PathBuf::from("git"),
            source,
        })?;
    Ok(String::from_utf8_lossy(&out.stdout).trim().to_string())
}

fn ok(status: std::process::ExitStatus, what: &str) -> Result<()> {
    if status.success() {
        Ok(())
    } else {
        Err(Error::Other(format!("git {what} failed")))
    }
}

pub fn is_repo(dir: &Path) -> bool {
    dir.join(".git").exists()
}

/// The `origin` URL of a working copy, if it has one.
pub fn remote_url(dir: &Path) -> Option<String> {
    let s = git_out(dir, &["remote", "get-url", "origin"]).ok()?;
    (!s.is_empty()).then_some(s)
}

/// Clone `url` into `dest`. If `dest` is already that same repo, adopt it.
pub fn clone(url: &str, dest: &Path) -> Result<()> {
    if is_repo(dest) {
        match remote_url(dest) {
            Some(u) if same_remote(&u, url) => {
                println!("  already cloned: {}", dest.display());
                return Ok(());
            }
            Some(u) => {
                return Err(Error::Other(format!(
                    "{} is a git repo, but its origin is a different one:\n  \
                     there: {u}\n  wanted: {url}\n\
                     Move it aside, or pass --path to clone somewhere else.",
                    dest.display()
                )))
            }
            None => {
                return Err(Error::Other(format!(
                    "{} is a git repo with no origin remote. Move it aside, or \
                     pass --path to clone somewhere else.",
                    dest.display()
                )))
            }
        }
    }
    if dest.exists() && dest.read_dir().is_ok_and(|mut d| d.next().is_some()) {
        return Err(Error::Other(format!(
            "{} exists and is not empty. Move it aside, or pass --path.",
            dest.display()
        )));
    }
    if let Some(parent) = dest.parent() {
        std::fs::create_dir_all(parent).map_err(|source| Error::Io {
            path: parent.to_path_buf(),
            source,
        })?;
    }
    println!("  git clone {url}");
    ok(
        git(None, &["clone", url, &dest.to_string_lossy()])?,
        "clone",
    )
}

/// Two URLs for the same repository, allowing for a trailing `.git` and a
/// trailing slash. Not an attempt at full URL equivalence -- just enough to
/// keep `github.com/x/y` and `github.com/x/y.git` from looking like a clash.
fn same_remote(a: &str, b: &str) -> bool {
    fn norm(s: &str) -> String {
        s.trim_end_matches('/').trim_end_matches(".git").to_string()
    }
    norm(a) == norm(b)
}

/// Uncommitted changes, in `git status --porcelain` form.
pub fn dirty(dir: &Path) -> Result<Vec<String>> {
    let out = git_out(dir, &["status", "--porcelain"])?;
    Ok(out
        .lines()
        .filter(|l| !l.trim().is_empty())
        .map(str::to_string)
        .collect())
}

/// Fast-forward the working copy to its remote.
///
/// `--ff-only`: a config repo should never grow a merge commit behind your
/// back. If the histories have diverged, that is a real conflict and you want
/// to see it in git, not have it resolved by a tool.
pub fn pull(dir: &Path) -> Result<()> {
    let d = dirty(dir)?;
    if !d.is_empty() {
        println!(
            "{}",
            color::changed(&format!(
                "  {} uncommitted change(s) -- pulling anyway, they stay put:",
                d.len()
            ))
        );
        for l in d.iter().take(10) {
            println!("    {l}");
        }
    }
    ok(git(Some(dir), &["pull", "--ff-only"])?, "pull")
}

/// Commit everything and push.
pub fn push(dir: &Path, message: Option<&str>, host: &str) -> Result<bool> {
    let d = dirty(dir)?;
    if d.is_empty() {
        // Still push: there may be commits made earlier that never went out.
        let ahead = git_out(dir, &["rev-list", "--count", "@{u}..HEAD"]).unwrap_or_default();
        if ahead == "0" {
            println!("  nothing to push -- the repo matches its remote.");
            return Ok(false);
        }
        println!("  {ahead} commit(s) to push");
        ok(git(Some(dir), &["push"])?, "push")?;
        return Ok(true);
    }

    println!("  staging {} change(s)", d.len());
    for l in d.iter().take(20) {
        println!("    {l}");
    }
    if d.len() > 20 {
        println!("    ... and {} more", d.len() - 20);
    }

    ok(git(Some(dir), &["add", "-A"])?, "add")?;
    let default = format!("{host}: config update");
    let msg = message.unwrap_or(&default);
    ok(git(Some(dir), &["commit", "-m", msg])?, "commit")?;
    ok(git(Some(dir), &["push"])?, "push")?;
    Ok(true)
}

/// One line describing where the repo stands, for `lami show`.
pub fn summary(dir: &Path) -> Option<String> {
    if !is_repo(dir) {
        return None;
    }
    let branch = git_out(dir, &["rev-parse", "--abbrev-ref", "HEAD"]).ok()?;
    let n = dirty(dir).map(|v| v.len()).unwrap_or(0);
    let state = if n == 0 {
        "clean".to_string()
    } else {
        format!("{n} uncommitted")
    };
    Some(match remote_url(dir) {
        Some(u) => format!("{u} [{branch}, {state}]"),
        None => format!("[{branch}, {state}] (no remote)"),
    })
}
